spring:
   main:
      banner-mode: off
   datasource:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/person?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      username: person
      password: 123
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate:
         ddl-auto: update
         use_sql_comments: true
      properties:
         hibernate:
            jdbc:
                time_zone: Asia/Baku

logging:
   level:
      org:
         springframework:
            transaction:
               interceptor: INFO

logstash:
   enabled: true
   appname: exchange-shims
   host: ${LOGSTASH_HOST:localhost}
   port: 5000
   queue-size: 512


