
spring:
   main:
      banner-mode: off
   datasource:
      url: jdbc:mysql://localhost:3306/person?useSSL=false
      username: root
      password:
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate:
         ddl-auto: update
         use_sql_comments: true
      properties:
         hibernate:
            jdbc:
                time_zone: Asia/Baku
      show-sql: false

